import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "@/redux/StoreProvider";
import Register from "@/components/register/Register";
import ClientOnly from "@/components/ClientOnly";
import Login from "@/components/login/Login";
import { Toaster } from "react-hot-toast";
import { Footer } from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* StoreProvider for redux */}
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster position="top-center" />
          <ClientOnly>
            <Register />
            <Login />
            <Navbar />
          </ClientOnly>
          {children}
          <Footer/>
        </body>
      </StoreProvider>
    </html>
  );
}
